//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVGStudentScores
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<decimal> AVGScore { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
