//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DvoechinikiVRazrezeGrupIDisciplin
    {
        public string GroupName { get; set; }
        public string Name { get; set; }
        public string FIO { get; set; }
        public System.DateTime Date { get; set; }
        public byte ValueGrade { get; set; }
    }
}
