//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int StudentID { get; set; }
        public System.DateTime Date { get; set; }
        public byte ValueGrade { get; set; }
        public int id { get; set; }
        public Nullable<int> RupID { get; set; }
    
        public virtual RUP RUP { get; set; }
        public virtual Students Students { get; set; }
    }
}
