//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveStudents
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string FIO { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.DateTime> DateOfExpulsion { get; set; }
    }
}
