//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VedomostOcenokStudentovVRazrezeGrupIDisciplin
    {
        public string GroupName { get; set; }
        public string DisciplineName { get; set; }
        public string StudentName { get; set; }
        public System.DateTime GradeDate { get; set; }
        public byte GradeValue { get; set; }
    }
}
